PRAGMA foreign_keys = ON;

UPDATE teams SET name = 'México', code = 'MEX', flag_code = 'mx', group_name = 'A', updated_at = CURRENT_TIMESTAMP WHERE id = 1;
UPDATE teams SET name = 'Sudáfrica', code = 'RSA', flag_code = 'za', group_name = 'A', updated_at = CURRENT_TIMESTAMP WHERE id = 2;
UPDATE teams SET name = 'Corea del Sur', code = 'KOR', flag_code = 'kr', group_name = 'A', updated_at = CURRENT_TIMESTAMP WHERE id = 3;
UPDATE teams SET name = 'República Checa', code = 'CZE', flag_code = 'cz', group_name = 'A', updated_at = CURRENT_TIMESTAMP WHERE id = 4;
UPDATE teams SET name = 'Canadá', code = 'CAN', flag_code = 'ca', group_name = 'B', updated_at = CURRENT_TIMESTAMP WHERE id = 5;
UPDATE teams SET name = 'Bosnia y Herzegovina', code = 'BIH', flag_code = 'ba', group_name = 'B', updated_at = CURRENT_TIMESTAMP WHERE id = 6;
UPDATE teams SET name = 'Qatar', code = 'QAT', flag_code = 'qa', group_name = 'B', updated_at = CURRENT_TIMESTAMP WHERE id = 7;
UPDATE teams SET name = 'Suiza', code = 'SUI', flag_code = 'ch', group_name = 'B', updated_at = CURRENT_TIMESTAMP WHERE id = 8;
UPDATE teams SET name = 'Brasil', code = 'BRA', flag_code = 'br', group_name = 'C', updated_at = CURRENT_TIMESTAMP WHERE id = 9;
UPDATE teams SET name = 'Marruecos', code = 'MAR', flag_code = 'ma', group_name = 'C', updated_at = CURRENT_TIMESTAMP WHERE id = 10;
UPDATE teams SET name = 'Haití', code = 'HAI', flag_code = 'ht', group_name = 'C', updated_at = CURRENT_TIMESTAMP WHERE id = 11;
UPDATE teams SET name = 'Escocia', code = 'SCO', flag_code = 'gb-sct', group_name = 'C', updated_at = CURRENT_TIMESTAMP WHERE id = 12;
UPDATE teams SET name = 'Estados Unidos', code = 'USA', flag_code = 'us', group_name = 'D', updated_at = CURRENT_TIMESTAMP WHERE id = 13;
UPDATE teams SET name = 'Paraguay', code = 'PAR', flag_code = 'py', group_name = 'D', updated_at = CURRENT_TIMESTAMP WHERE id = 14;
UPDATE teams SET name = 'Australia', code = 'AUS', flag_code = 'au', group_name = 'D', updated_at = CURRENT_TIMESTAMP WHERE id = 15;
UPDATE teams SET name = 'Turquía', code = 'TUR', flag_code = 'tr', group_name = 'D', updated_at = CURRENT_TIMESTAMP WHERE id = 16;
UPDATE teams SET name = 'Alemania', code = 'GER', flag_code = 'de', group_name = 'E', updated_at = CURRENT_TIMESTAMP WHERE id = 17;
UPDATE teams SET name = 'Curazao', code = 'CUW', flag_code = 'cw', group_name = 'E', updated_at = CURRENT_TIMESTAMP WHERE id = 18;
UPDATE teams SET name = 'Costa de Marfil', code = 'CIV', flag_code = 'ci', group_name = 'E', updated_at = CURRENT_TIMESTAMP WHERE id = 19;
UPDATE teams SET name = 'Ecuador', code = 'ECU', flag_code = 'ec', group_name = 'E', updated_at = CURRENT_TIMESTAMP WHERE id = 20;
UPDATE teams SET name = 'Países Bajos', code = 'NED', flag_code = 'nl', group_name = 'F', updated_at = CURRENT_TIMESTAMP WHERE id = 21;
UPDATE teams SET name = 'Japón', code = 'JPN', flag_code = 'jp', group_name = 'F', updated_at = CURRENT_TIMESTAMP WHERE id = 22;
UPDATE teams SET name = 'Suecia', code = 'SWE', flag_code = 'se', group_name = 'F', updated_at = CURRENT_TIMESTAMP WHERE id = 23;
UPDATE teams SET name = 'Túnez', code = 'TUN', flag_code = 'tn', group_name = 'F', updated_at = CURRENT_TIMESTAMP WHERE id = 24;
UPDATE teams SET name = 'Bélgica', code = 'BEL', flag_code = 'be', group_name = 'G', updated_at = CURRENT_TIMESTAMP WHERE id = 25;
UPDATE teams SET name = 'Egipto', code = 'EGY', flag_code = 'eg', group_name = 'G', updated_at = CURRENT_TIMESTAMP WHERE id = 26;
UPDATE teams SET name = 'Irán', code = 'IRN', flag_code = 'ir', group_name = 'G', updated_at = CURRENT_TIMESTAMP WHERE id = 27;
UPDATE teams SET name = 'Nueva Zelanda', code = 'NZL', flag_code = 'nz', group_name = 'G', updated_at = CURRENT_TIMESTAMP WHERE id = 28;
UPDATE teams SET name = 'España', code = 'ESP', flag_code = 'es', group_name = 'H', updated_at = CURRENT_TIMESTAMP WHERE id = 29;
UPDATE teams SET name = 'Cabo Verde', code = 'CPV', flag_code = 'cv', group_name = 'H', updated_at = CURRENT_TIMESTAMP WHERE id = 30;
UPDATE teams SET name = 'Arabia Saudita', code = 'KSA', flag_code = 'sa', group_name = 'H', updated_at = CURRENT_TIMESTAMP WHERE id = 31;
UPDATE teams SET name = 'Uruguay', code = 'URU', flag_code = 'uy', group_name = 'H', updated_at = CURRENT_TIMESTAMP WHERE id = 32;
UPDATE teams SET name = 'Francia', code = 'FRA', flag_code = 'fr', group_name = 'I', updated_at = CURRENT_TIMESTAMP WHERE id = 33;
UPDATE teams SET name = 'Senegal', code = 'SEN', flag_code = 'sn', group_name = 'I', updated_at = CURRENT_TIMESTAMP WHERE id = 34;
UPDATE teams SET name = 'Irak', code = 'IRQ', flag_code = 'iq', group_name = 'I', updated_at = CURRENT_TIMESTAMP WHERE id = 35;
UPDATE teams SET name = 'Noruega', code = 'NOR', flag_code = 'no', group_name = 'I', updated_at = CURRENT_TIMESTAMP WHERE id = 36;
UPDATE teams SET name = 'Argentina', code = 'ARG', flag_code = 'ar', group_name = 'J', updated_at = CURRENT_TIMESTAMP WHERE id = 37;
UPDATE teams SET name = 'Argelia', code = 'ALG', flag_code = 'dz', group_name = 'J', updated_at = CURRENT_TIMESTAMP WHERE id = 38;
UPDATE teams SET name = 'Austria', code = 'AUT', flag_code = 'at', group_name = 'J', updated_at = CURRENT_TIMESTAMP WHERE id = 39;
UPDATE teams SET name = 'Jordania', code = 'JOR', flag_code = 'jo', group_name = 'J', updated_at = CURRENT_TIMESTAMP WHERE id = 40;
UPDATE teams SET name = 'Portugal', code = 'POR', flag_code = 'pt', group_name = 'K', updated_at = CURRENT_TIMESTAMP WHERE id = 41;
UPDATE teams SET name = 'RD Congo', code = 'COD', flag_code = 'cd', group_name = 'K', updated_at = CURRENT_TIMESTAMP WHERE id = 42;
UPDATE teams SET name = 'Uzbekistán', code = 'UZB', flag_code = 'uz', group_name = 'K', updated_at = CURRENT_TIMESTAMP WHERE id = 43;
UPDATE teams SET name = 'Colombia', code = 'COL', flag_code = 'co', group_name = 'K', updated_at = CURRENT_TIMESTAMP WHERE id = 44;
UPDATE teams SET name = 'Inglaterra', code = 'ENG', flag_code = 'gb-eng', group_name = 'L', updated_at = CURRENT_TIMESTAMP WHERE id = 45;
UPDATE teams SET name = 'Croacia', code = 'CRO', flag_code = 'hr', group_name = 'L', updated_at = CURRENT_TIMESTAMP WHERE id = 46;
UPDATE teams SET name = 'Ghana', code = 'GHA', flag_code = 'gh', group_name = 'L', updated_at = CURRENT_TIMESTAMP WHERE id = 47;
UPDATE teams SET name = 'Panamá', code = 'PAN', flag_code = 'pa', group_name = 'L', updated_at = CURRENT_TIMESTAMP WHERE id = 48;

