PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO scoring_rules (id, exact_score_points, correct_winner_points, correct_draw_points, goal_difference_points, champion_bonus_points, runner_up_bonus_points, third_place_bonus_points, fourth_place_bonus_points) VALUES (1, 5, 3, 3, 1, 10, 6, 4, 2);

INSERT OR IGNORE INTO app_settings (key, value) VALUES ('PREDICTIONS_LOCKED', 'false');

INSERT OR IGNORE INTO users (id, name, email, password_hash, role) VALUES (1, 'Administrador', 'admin@prode.local', 'pbkdf2_sha256$100000$D9Pr5PkfUse0qhD9xRct6A==$jTqAifK9iLPjNC9PF9sFWz0qS1pA8H6KhYcucDZlsuM=', 'ADMIN');

INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (1, 'México', 'MEX', 'mx', 'A');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (2, 'Sudáfrica', 'RSA', 'za', 'A');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (3, 'Corea del Sur', 'KOR', 'kr', 'A');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (4, 'República Checa', 'CZE', 'cz', 'A');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (5, 'Canadá', 'CAN', 'ca', 'B');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (6, 'Bosnia y Herzegovina', 'BIH', 'ba', 'B');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (7, 'Qatar', 'QAT', 'qa', 'B');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (8, 'Suiza', 'SUI', 'ch', 'B');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (9, 'Brasil', 'BRA', 'br', 'C');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (10, 'Marruecos', 'MAR', 'ma', 'C');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (11, 'Haití', 'HAI', 'ht', 'C');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (12, 'Escocia', 'SCO', 'gb-sct', 'C');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (13, 'Estados Unidos', 'USA', 'us', 'D');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (14, 'Paraguay', 'PAR', 'py', 'D');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (15, 'Australia', 'AUS', 'au', 'D');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (16, 'Turquía', 'TUR', 'tr', 'D');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (17, 'Alemania', 'GER', 'de', 'E');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (18, 'Curazao', 'CUW', 'cw', 'E');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (19, 'Costa de Marfil', 'CIV', 'ci', 'E');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (20, 'Ecuador', 'ECU', 'ec', 'E');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (21, 'Países Bajos', 'NED', 'nl', 'F');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (22, 'Japón', 'JPN', 'jp', 'F');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (23, 'Suecia', 'SWE', 'se', 'F');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (24, 'Túnez', 'TUN', 'tn', 'F');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (25, 'Bélgica', 'BEL', 'be', 'G');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (26, 'Egipto', 'EGY', 'eg', 'G');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (27, 'Irán', 'IRN', 'ir', 'G');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (28, 'Nueva Zelanda', 'NZL', 'nz', 'G');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (29, 'España', 'ESP', 'es', 'H');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (30, 'Cabo Verde', 'CPV', 'cv', 'H');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (31, 'Arabia Saudita', 'KSA', 'sa', 'H');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (32, 'Uruguay', 'URU', 'uy', 'H');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (33, 'Francia', 'FRA', 'fr', 'I');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (34, 'Senegal', 'SEN', 'sn', 'I');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (35, 'Irak', 'IRQ', 'iq', 'I');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (36, 'Noruega', 'NOR', 'no', 'I');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (37, 'Argentina', 'ARG', 'ar', 'J');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (38, 'Argelia', 'ALG', 'dz', 'J');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (39, 'Austria', 'AUT', 'at', 'J');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (40, 'Jordania', 'JOR', 'jo', 'J');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (41, 'Portugal', 'POR', 'pt', 'K');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (42, 'RD Congo', 'COD', 'cd', 'K');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (43, 'Uzbekistán', 'UZB', 'uz', 'K');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (44, 'Colombia', 'COL', 'co', 'K');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (45, 'Inglaterra', 'ENG', 'gb-eng', 'L');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (46, 'Croacia', 'CRO', 'hr', 'L');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (47, 'Ghana', 'GHA', 'gh', 'L');
INSERT OR IGNORE INTO teams (id, name, code, flag_code, group_name) VALUES (48, 'Panamá', 'PAN', 'pa', 'L');

INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (1, 'Fase de grupos', 'A', 1, 2, '2026-06-11T22:00:00Z', 'SCHEDULED', 'Ciudad de México', 1);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (2, 'Fase de grupos', 'A', 3, 4, '2026-06-12T01:00:00Z', 'SCHEDULED', 'Guadalajara', 2);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (3, 'Fase de grupos', 'A', 1, 3, '2026-06-12T04:00:00Z', 'SCHEDULED', 'Monterrey', 3);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (4, 'Fase de grupos', 'A', 4, 2, '2026-06-12T07:00:00Z', 'SCHEDULED', 'Toronto', 4);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (5, 'Fase de grupos', 'A', 4, 1, '2026-06-12T10:00:00Z', 'SCHEDULED', 'Vancouver', 5);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (6, 'Fase de grupos', 'A', 2, 3, '2026-06-12T13:00:00Z', 'SCHEDULED', 'Los Angeles', 6);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (7, 'Fase de grupos', 'B', 5, 6, '2026-06-12T16:00:00Z', 'SCHEDULED', 'Seattle', 7);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (8, 'Fase de grupos', 'B', 7, 8, '2026-06-12T19:00:00Z', 'SCHEDULED', 'San Francisco Bay Area', 8);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (9, 'Fase de grupos', 'B', 5, 7, '2026-06-12T22:00:00Z', 'SCHEDULED', 'Dallas', 9);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (10, 'Fase de grupos', 'B', 8, 6, '2026-06-13T01:00:00Z', 'SCHEDULED', 'Houston', 10);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (11, 'Fase de grupos', 'B', 8, 5, '2026-06-13T04:00:00Z', 'SCHEDULED', 'Kansas City', 11);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (12, 'Fase de grupos', 'B', 6, 7, '2026-06-13T07:00:00Z', 'SCHEDULED', 'Atlanta', 12);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (13, 'Fase de grupos', 'C', 9, 10, '2026-06-13T10:00:00Z', 'SCHEDULED', 'Miami', 13);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (14, 'Fase de grupos', 'C', 11, 12, '2026-06-13T13:00:00Z', 'SCHEDULED', 'Boston', 14);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (15, 'Fase de grupos', 'C', 9, 11, '2026-06-13T16:00:00Z', 'SCHEDULED', 'Philadelphia', 15);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (16, 'Fase de grupos', 'C', 12, 10, '2026-06-13T19:00:00Z', 'SCHEDULED', 'New York/New Jersey', 16);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (17, 'Fase de grupos', 'C', 12, 9, '2026-06-13T22:00:00Z', 'SCHEDULED', 'Ciudad de México', 17);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (18, 'Fase de grupos', 'C', 10, 11, '2026-06-14T01:00:00Z', 'SCHEDULED', 'Guadalajara', 18);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (19, 'Fase de grupos', 'D', 13, 14, '2026-06-14T04:00:00Z', 'SCHEDULED', 'Monterrey', 19);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (20, 'Fase de grupos', 'D', 15, 16, '2026-06-14T07:00:00Z', 'SCHEDULED', 'Toronto', 20);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (21, 'Fase de grupos', 'D', 13, 15, '2026-06-14T10:00:00Z', 'SCHEDULED', 'Vancouver', 21);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (22, 'Fase de grupos', 'D', 16, 14, '2026-06-14T13:00:00Z', 'SCHEDULED', 'Los Angeles', 22);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (23, 'Fase de grupos', 'D', 16, 13, '2026-06-14T16:00:00Z', 'SCHEDULED', 'Seattle', 23);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (24, 'Fase de grupos', 'D', 14, 15, '2026-06-14T19:00:00Z', 'SCHEDULED', 'San Francisco Bay Area', 24);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (25, 'Fase de grupos', 'E', 17, 18, '2026-06-14T22:00:00Z', 'SCHEDULED', 'Dallas', 25);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (26, 'Fase de grupos', 'E', 19, 20, '2026-06-15T01:00:00Z', 'SCHEDULED', 'Houston', 26);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (27, 'Fase de grupos', 'E', 17, 19, '2026-06-15T04:00:00Z', 'SCHEDULED', 'Kansas City', 27);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (28, 'Fase de grupos', 'E', 20, 18, '2026-06-15T07:00:00Z', 'SCHEDULED', 'Atlanta', 28);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (29, 'Fase de grupos', 'E', 20, 17, '2026-06-15T10:00:00Z', 'SCHEDULED', 'Miami', 29);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (30, 'Fase de grupos', 'E', 18, 19, '2026-06-15T13:00:00Z', 'SCHEDULED', 'Boston', 30);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (31, 'Fase de grupos', 'F', 21, 22, '2026-06-15T16:00:00Z', 'SCHEDULED', 'Philadelphia', 31);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (32, 'Fase de grupos', 'F', 23, 24, '2026-06-15T19:00:00Z', 'SCHEDULED', 'New York/New Jersey', 32);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (33, 'Fase de grupos', 'F', 21, 23, '2026-06-15T22:00:00Z', 'SCHEDULED', 'Ciudad de México', 33);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (34, 'Fase de grupos', 'F', 24, 22, '2026-06-16T01:00:00Z', 'SCHEDULED', 'Guadalajara', 34);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (35, 'Fase de grupos', 'F', 24, 21, '2026-06-16T04:00:00Z', 'SCHEDULED', 'Monterrey', 35);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (36, 'Fase de grupos', 'F', 22, 23, '2026-06-16T07:00:00Z', 'SCHEDULED', 'Toronto', 36);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (37, 'Fase de grupos', 'G', 25, 26, '2026-06-16T10:00:00Z', 'SCHEDULED', 'Vancouver', 37);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (38, 'Fase de grupos', 'G', 27, 28, '2026-06-16T13:00:00Z', 'SCHEDULED', 'Los Angeles', 38);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (39, 'Fase de grupos', 'G', 25, 27, '2026-06-16T16:00:00Z', 'SCHEDULED', 'Seattle', 39);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (40, 'Fase de grupos', 'G', 28, 26, '2026-06-16T19:00:00Z', 'SCHEDULED', 'San Francisco Bay Area', 40);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (41, 'Fase de grupos', 'G', 28, 25, '2026-06-16T22:00:00Z', 'SCHEDULED', 'Dallas', 41);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (42, 'Fase de grupos', 'G', 26, 27, '2026-06-17T01:00:00Z', 'SCHEDULED', 'Houston', 42);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (43, 'Fase de grupos', 'H', 29, 30, '2026-06-17T04:00:00Z', 'SCHEDULED', 'Kansas City', 43);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (44, 'Fase de grupos', 'H', 31, 32, '2026-06-17T07:00:00Z', 'SCHEDULED', 'Atlanta', 44);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (45, 'Fase de grupos', 'H', 29, 31, '2026-06-17T10:00:00Z', 'SCHEDULED', 'Miami', 45);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (46, 'Fase de grupos', 'H', 32, 30, '2026-06-17T13:00:00Z', 'SCHEDULED', 'Boston', 46);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (47, 'Fase de grupos', 'H', 32, 29, '2026-06-17T16:00:00Z', 'SCHEDULED', 'Philadelphia', 47);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (48, 'Fase de grupos', 'H', 30, 31, '2026-06-17T19:00:00Z', 'SCHEDULED', 'New York/New Jersey', 48);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (49, 'Fase de grupos', 'I', 33, 34, '2026-06-17T22:00:00Z', 'SCHEDULED', 'Ciudad de México', 49);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (50, 'Fase de grupos', 'I', 35, 36, '2026-06-18T01:00:00Z', 'SCHEDULED', 'Guadalajara', 50);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (51, 'Fase de grupos', 'I', 33, 35, '2026-06-18T04:00:00Z', 'SCHEDULED', 'Monterrey', 51);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (52, 'Fase de grupos', 'I', 36, 34, '2026-06-18T07:00:00Z', 'SCHEDULED', 'Toronto', 52);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (53, 'Fase de grupos', 'I', 36, 33, '2026-06-18T10:00:00Z', 'SCHEDULED', 'Vancouver', 53);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (54, 'Fase de grupos', 'I', 34, 35, '2026-06-18T13:00:00Z', 'SCHEDULED', 'Los Angeles', 54);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (55, 'Fase de grupos', 'J', 37, 38, '2026-06-18T16:00:00Z', 'SCHEDULED', 'Seattle', 55);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (56, 'Fase de grupos', 'J', 39, 40, '2026-06-18T19:00:00Z', 'SCHEDULED', 'San Francisco Bay Area', 56);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (57, 'Fase de grupos', 'J', 37, 39, '2026-06-18T22:00:00Z', 'SCHEDULED', 'Dallas', 57);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (58, 'Fase de grupos', 'J', 40, 38, '2026-06-19T01:00:00Z', 'SCHEDULED', 'Houston', 58);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (59, 'Fase de grupos', 'J', 40, 37, '2026-06-19T04:00:00Z', 'SCHEDULED', 'Kansas City', 59);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (60, 'Fase de grupos', 'J', 38, 39, '2026-06-19T07:00:00Z', 'SCHEDULED', 'Atlanta', 60);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (61, 'Fase de grupos', 'K', 41, 42, '2026-06-19T10:00:00Z', 'SCHEDULED', 'Miami', 61);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (62, 'Fase de grupos', 'K', 43, 44, '2026-06-19T13:00:00Z', 'SCHEDULED', 'Boston', 62);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (63, 'Fase de grupos', 'K', 41, 43, '2026-06-19T16:00:00Z', 'SCHEDULED', 'Philadelphia', 63);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (64, 'Fase de grupos', 'K', 44, 42, '2026-06-19T19:00:00Z', 'SCHEDULED', 'New York/New Jersey', 64);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (65, 'Fase de grupos', 'K', 44, 41, '2026-06-19T22:00:00Z', 'SCHEDULED', 'Ciudad de México', 65);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (66, 'Fase de grupos', 'K', 42, 43, '2026-06-20T01:00:00Z', 'SCHEDULED', 'Guadalajara', 66);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (67, 'Fase de grupos', 'L', 45, 46, '2026-06-20T04:00:00Z', 'SCHEDULED', 'Monterrey', 67);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (68, 'Fase de grupos', 'L', 47, 48, '2026-06-20T07:00:00Z', 'SCHEDULED', 'Toronto', 68);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (69, 'Fase de grupos', 'L', 45, 47, '2026-06-20T10:00:00Z', 'SCHEDULED', 'Vancouver', 69);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (70, 'Fase de grupos', 'L', 48, 46, '2026-06-20T13:00:00Z', 'SCHEDULED', 'Los Angeles', 70);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (71, 'Fase de grupos', 'L', 48, 45, '2026-06-20T16:00:00Z', 'SCHEDULED', 'Seattle', 71);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (72, 'Fase de grupos', 'L', 46, 47, '2026-06-20T19:00:00Z', 'SCHEDULED', 'San Francisco Bay Area', 72);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (73, '32avos de final', NULL, NULL, NULL, '2026-06-28T18:00:00Z', 'SCHEDULED', 'Dallas', 73);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (74, '32avos de final', NULL, NULL, NULL, '2026-06-28T22:00:00Z', 'SCHEDULED', 'Houston', 74);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (75, '32avos de final', NULL, NULL, NULL, '2026-06-29T02:00:00Z', 'SCHEDULED', 'Kansas City', 75);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (76, '32avos de final', NULL, NULL, NULL, '2026-06-29T06:00:00Z', 'SCHEDULED', 'Atlanta', 76);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (77, '32avos de final', NULL, NULL, NULL, '2026-06-29T10:00:00Z', 'SCHEDULED', 'Miami', 77);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (78, '32avos de final', NULL, NULL, NULL, '2026-06-29T14:00:00Z', 'SCHEDULED', 'Boston', 78);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (79, '32avos de final', NULL, NULL, NULL, '2026-06-29T18:00:00Z', 'SCHEDULED', 'Philadelphia', 79);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (80, '32avos de final', NULL, NULL, NULL, '2026-06-29T22:00:00Z', 'SCHEDULED', 'New York/New Jersey', 80);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (81, '32avos de final', NULL, NULL, NULL, '2026-06-30T02:00:00Z', 'SCHEDULED', 'Ciudad de México', 81);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (82, '32avos de final', NULL, NULL, NULL, '2026-06-30T06:00:00Z', 'SCHEDULED', 'Guadalajara', 82);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (83, '32avos de final', NULL, NULL, NULL, '2026-06-30T10:00:00Z', 'SCHEDULED', 'Monterrey', 83);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (84, '32avos de final', NULL, NULL, NULL, '2026-06-30T14:00:00Z', 'SCHEDULED', 'Toronto', 84);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (85, '32avos de final', NULL, NULL, NULL, '2026-06-30T18:00:00Z', 'SCHEDULED', 'Vancouver', 85);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (86, '32avos de final', NULL, NULL, NULL, '2026-06-30T22:00:00Z', 'SCHEDULED', 'Los Angeles', 86);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (87, '32avos de final', NULL, NULL, NULL, '2026-07-01T02:00:00Z', 'SCHEDULED', 'Seattle', 87);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (88, '32avos de final', NULL, NULL, NULL, '2026-07-01T06:00:00Z', 'SCHEDULED', 'San Francisco Bay Area', 88);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (89, 'Octavos de final', NULL, NULL, NULL, '2026-07-01T18:00:00Z', 'SCHEDULED', 'Dallas', 89);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (90, 'Octavos de final', NULL, NULL, NULL, '2026-07-01T22:00:00Z', 'SCHEDULED', 'Houston', 90);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (91, 'Octavos de final', NULL, NULL, NULL, '2026-07-02T02:00:00Z', 'SCHEDULED', 'Kansas City', 91);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (92, 'Octavos de final', NULL, NULL, NULL, '2026-07-02T06:00:00Z', 'SCHEDULED', 'Atlanta', 92);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (93, 'Octavos de final', NULL, NULL, NULL, '2026-07-02T10:00:00Z', 'SCHEDULED', 'Miami', 93);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (94, 'Octavos de final', NULL, NULL, NULL, '2026-07-02T14:00:00Z', 'SCHEDULED', 'Boston', 94);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (95, 'Octavos de final', NULL, NULL, NULL, '2026-07-02T18:00:00Z', 'SCHEDULED', 'Philadelphia', 95);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (96, 'Octavos de final', NULL, NULL, NULL, '2026-07-02T22:00:00Z', 'SCHEDULED', 'New York/New Jersey', 96);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (97, 'Cuartos de final', NULL, NULL, NULL, '2026-07-04T18:00:00Z', 'SCHEDULED', 'Ciudad de México', 97);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (98, 'Cuartos de final', NULL, NULL, NULL, '2026-07-04T22:00:00Z', 'SCHEDULED', 'Guadalajara', 98);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (99, 'Cuartos de final', NULL, NULL, NULL, '2026-07-05T02:00:00Z', 'SCHEDULED', 'Monterrey', 99);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (100, 'Cuartos de final', NULL, NULL, NULL, '2026-07-05T06:00:00Z', 'SCHEDULED', 'Toronto', 100);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (101, 'Semifinal', NULL, NULL, NULL, '2026-07-07T18:00:00Z', 'SCHEDULED', 'Vancouver', 101);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (102, 'Semifinal', NULL, NULL, NULL, '2026-07-07T22:00:00Z', 'SCHEDULED', 'Los Angeles', 102);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (103, 'Tercer puesto', NULL, NULL, NULL, '2026-07-10T18:00:00Z', 'SCHEDULED', 'Seattle', 103);
INSERT OR IGNORE INTO matches (id, stage, group_name, home_team_id, away_team_id, starts_at, status, venue, match_order) VALUES (104, 'Final', NULL, NULL, NULL, '2026-07-13T18:00:00Z', 'SCHEDULED', 'San Francisco Bay Area', 104);