name = "prode-mundial-2026-api"
main = "src/index.ts"
compatibility_date = "2025-01-29"

[vars]
APP_ENV = "production"
CORS_ORIGIN = "https://prodemundial2026-aci.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "prode_mundial_2026"
database_id = "cffcf0cc-dd5e-4c00-891d-658d0884b27b"
migrations_dir = "migrations"

[triggers]
crons = ["*/30 * * * *"]
